
public abstract class Meter {
	protected int consumed;
	protected int generated;
	protected boolean canGenerate;
	
	public Meter(int consumed, int generated, boolean canGenerate){
		this.consumed = consumed;
		this.generated = generated;
		this.canGenerate = canGenerate;
	}
	
	public int getConsumed(){ // return how much electricity/gas/water was consumed
		return consumed;
	}
	
	public int getGenerated(){ // return how much electricity/gas/water was generated
		return generated;
	}
	
	public boolean canGenerate(){ // return if the resource can be generated
		return canGenerate;
	}
	
	public abstract String getType(); // return the type of meter: electric/gas/water

	
	public void incrementConsumed(int amount){ // increment how much was consumed by a certain amount
		consumed += amount;
	}
	
	public void incrementGenerated(int amount){ // increment how much was generated by a certain amount
		generated += amount;
	}
	
	public void decrementConsumed(int amount){ // decrement how much was consumed by a certain amount
		consumed -= amount;
	}
	
	public abstract void show(); // show how much electricity/gas/water was used
	
	public abstract String getName(); // get the name of the meter 
}
